### ISSUE TITLE
Detector confidence value may be incorrect

### ISSUE THREAD

**Issue by kuri122333** [nizhf/hoi-prediction-gaze-transformer#10]
Thank you for the great repo! I checked the [run.py](https://github.com/nizhf/hoi-prediction-gaze-transformer/blob/main/run.py) and found one area that I think you should check.

> File "hoi-prediction-gaze-transformer/modules/object_tracking/yolov5_deepsort.py", line 183,
> for out, conf in zip(deepsort_outs, confs):

In the above section, “deepsort_outs” are sorted ID from the object tracker, while “confs” are not sorted with refer to the "deepsort_outs". I think there are mismatches.

Although this could be my misunderstanding, could you check it?

Thanks in advance.

**Comment by nizhf** [comment]
Thank you for your comments. Yes, I think you are right. The confs here do not match the tracker results.

A quick workaround is maybe to add a line after this https://github.com/nizhf/hoi-prediction-gaze-transformer/blob/main/modules/object_tracking/deep_sort/deep_sort.py#L49 like `conf = det.confidence` and append `conf` to the output list (L55). 
Then here https://github.com/nizhf/hoi-prediction-gaze-transformer/blob/main/modules/object_tracking/yolov5_deepsort.py#L192 you can change the source of `confidence_list` to the corresponding part in the `out`.

**Comment by kuri122333** [comment]
I understood!
Thanks for the feedback. I will try it.
