### ISSUE TITLE
There is no val_frame_annots.json

### ISSUE THREAD

**Issue by ThePassedWind** [nizhf/hoi-prediction-gaze-transformer#2]
The file is not in this download site~
(https://drive.google.com/drive/folders/0B94KbEj1tO9nfi05YmlvS1ctdWRxVVhISVQ5b2FQN293MTRhMzFNY1p4QWY0TzhQVkR4ekk?resourcekey=0-TwBoRuVnDeRZCpgzACYPsA)
Could you please help me find this json doc? Maybe det_val_frame_annots.json(existed) is not equal to val_frame_annots.json?

**Comment by nizhf** [comment]
As described in [train.md](https://github.com/nizhf/hoi-prediction-gaze-transformer/blob/main/train.md), some JSON files (small files) are from the VidHOI repo: https://github.com/coldmanck/VidHOI/tree/master/slowfast/datasets/vidor-github

**Comment by ThePassedWind** [comment]
Got it! Thanks!
