### ISSUE TITLE
There is no "train_frame_gazes_gt_bbox.dat"

### ISSUE THREAD

**Issue by ThePassedWind** [nizhf/hoi-prediction-gaze-transformer#3]
Hi!
When I tried to train a model, the error occurred:
`FileNotFoundError: [Errno 2] No such file or directory: 'VidOR/VidHOI_gaze/train_frame_gazes_gt_bbox.dat'`
Could you please share the related data?

**Comment by nizhf** [comment]
You can use these two scripts to generate the gaze data: https://github.com/nizhf/hoi-prediction-gaze-transformer/blob/main/misc_scripts/vidhoi_gt_gaze_extraction.ipynb with ground-truth human bbox, for training and validation; https://github.com/nizhf/hoi-prediction-gaze-transformer/blob/main/misc_scripts/vidhoi_yolov5_deepsort_gaze_extraction.ipynb with detected human bbox, only for validation.
Also see https://github.com/nizhf/hoi-prediction-gaze-transformer/blob/main/train.md#object-detection-and-gaze-features

**Comment by ThePassedWind** [comment]
Got it!
Thanks for your instant reply!
