### ISSUE TITLE
Could you share your pretrained model?

### ISSUE THREAD

**Issue by ThePassedWind** [nizhf/hoi-prediction-gaze-transformer#4]

**Comment by ThePassedWind** [comment]
And I guess you are Chinese? Could I add your Wechat and ask more detailed questions?

**Comment by nizhf** [comment]
The download links for pre-trained models are given here https://github.com/nizhf/hoi-prediction-gaze-transformer/blob/main/train.md#evaluation

**Comment by nizhf** [comment]
然后我微信号是nizhf1
