### ISSUE TITLE
There is no "parser.add_argument("--detection") in eval_inference_vidhoi.py

### ISSUE THREAD

**Issue by ThePassedWind** [nizhf/hoi-prediction-gaze-transformer#5]
I'd like to train a model of Detection Mode, but your training code is maybe only for Oracle Mode.

**Comment by nizhf** [comment]
We always train the model first with ground-truth bbox, then test with detected bbox. We do not have the ground-truth interaction for detected human-object pairs.

**Comment by ThePassedWind** [comment]
Got it
