### ISSUE TITLE
torchvision==0.11.0 is yanked help!!!

### ISSUE THREAD

**Issue by TanishqAgarwal29** [nizhf/hoi-prediction-gaze-transformer#7]
Hello Owner,

When I am using the code:

!conda install mamba -c conda-forge  # install mamba in base environment
!mamba create -n hoi_torch110 python=3.9 -c conda-forge 
!conda activate hoi_torch110  
!mamba install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 torchtext==0.11.0 cudatoolkit=11.3 matplotlib numpy opencv Pillow PyYAML requests scipy tqdm tensorboard wandb pandas seaborn Cython easydict gdown scikit-learn imageio notebook ipywidgets black -c pytorch -c conda-forge

Its not getting executed as torchvision==0.11.0 is yanked means its not available so there is no use of torch version 1.10.0 so its not getting executed in google colab, please suggest me a different code for this.

Warm Regards,
Tanishq Agarwal

**Comment by nizhf** [comment]
Hello,

Thank you for your interest in our work!
I tried this code on my local machine. It seems like opencv causes the incompatibility problem. 
Maybe you can use pip instead of mamba to install opencv.
Simply remove `opencv` from that `mamba install ...` line, then execute `pip install opencv-python`.
I tested some cv2 image operations and they worked properly. Please let me know whether this also works for your environment.

Best,
Zhifan Ni

**Comment by TanishqAgarwal29** [comment]
I am getting a new error when I am executing the next line of code

# Detection
%cd /content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer
!python run.py --source /content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer/ABA Therapy_ Daniel - Communication.mp4 --out /content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer/rohan --future 1 --hoi-thres 0.3 --print
# For anticipation, set future to 1, 3, 5, or 7

AND THE ERROR I AM GETTING IN GOOGLE COLAB IS


# Detection
%cd /content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer
!python run.py --source /content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer/ABA Therapy_ Daniel - Communication.mp4 --out /content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer/rohan --future 1 --hoi-thres 0.3 --print
# For anticipation, set future to 1, 3, 5, or 7
/content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer/run.py", line 19, in <module>
    from common.transforms import STTranTransform, YOLOv5Transform
  File "/content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer/common/transforms.py", line 7, in <module>
    from modules.object_tracking.yolov5.utils.augmentations import letterbox
  File "/content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer/modules/object_tracking/__init__.py", line 4, in <module>
    from .feature_backbone import FeatureExtractionResNet101, FeatureExtractionResNet50
  File "/content/drive/MyDrive/Colab Notebooks/hoi-prediction-gaze-transformer/modules/object_tracking/feature_backbone.py", line 7, in <module>
    from torchvision.models.resnet import ResNet, Bottleneck, model_urls
ImportError: cannot import name 'model_urls' from 'torchvision.models.resnet' (/usr/local/lib/python3.10/dist-packages/torchvision/models/resnet.py)

PLEASE SUGGEST ME I NEED THIS MODEL TO WORK I HAVE SOME REALLY URGENT NEED OF THIS MODEL PLEASE HELP ME OWNER!!

**Comment by nizhf** [comment]
Which torchvision version are you using? From maybe 0.14.0, pytorch removes that model_url.
